CREATE DATABASE IF NOT EXISTS project;
USE project;

CREATE TABLE IF NOT EXISTS users
(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
user_login VARCHAR(50) NOT NULL UNIQUE,
user_password VARCHAR(50) NOT NULL,
nif VARCHAR(10) NOT NULL UNIQUE,
email VARCHAR(50) NOT NULL UNIQUE,
name VARCHAR(50) NOT NULL,
birthday DATE NOT NULL,
tlf VARCHAR(50),
address VARCHAR(50),
avatar_img VARCHAR(50),
create_user TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
update_user TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS travels
(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
locality VARCHAR(50) NOT NULL,
departure_date DATE NOT NULL,
arrival_date DATE NOT NULL,
category varchar(50) NOT NULL,
budget FLOAT DEFAULT 0,
id_user INT UNSIGNED NOT NULL REFERENCES users,
create_travel TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
update_travel TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages
(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
msg_text VARCHAR(255) NOT NULL,
id_user INT UNSIGNED REFERENCES users,
create_message TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
update_message TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rates
(
id INT UNSIGNED PRIMARY KEY NOT NULL,
rate_text VARCHAR(255) NOT NULL,
points INT NOT NULL,
id_user INT UNSIGNED REFERENCES users,
create_rate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
update_rate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_choose_travel
(
id_user INT UNSIGNED REFERENCES users,
id_travel INT UNSIGNED REFERENCES travels,
choose_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id_user, id_travel),
create_user_choose_travel TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
update_user_choose_travel TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



